# Generated by Django 5.2.16 on 2026-07-26 23:49

import apps.test_platform.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApprovedKnowledgeEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_id",
                    models.CharField(max_length=128, verbose_name="所属系统"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="知识标题")),
                ("content", models.TextField(verbose_name="知识内容")),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        help_text="可上传 Word、PDF、Markdown、TXT、Excel、JSON 等常见文档；系统会提取文字供审核。",
                        upload_to="test_platform/knowledge/%Y/%m/",
                        verbose_name="导入文件（可选）",
                    ),
                ),
                (
                    "scope_id",
                    models.CharField(
                        default=apps.test_platform.models._knowledge_scope_id,
                        editable=False,
                        max_length=128,
                        unique=True,
                    ),
                ),
                (
                    "knowledge_id",
                    models.CharField(
                        default=apps.test_platform.models._knowledge_id,
                        editable=False,
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1, editable=False)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "待审核"), ("approved", "已发布")],
                        db_index=True,
                        default="draft",
                        editable=False,
                        max_length=16,
                        verbose_name="发布状态",
                    ),
                ),
                (
                    "approval_id",
                    models.CharField(blank=True, editable=False, max_length=128),
                ),
                (
                    "approved_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                (
                    "content_hash",
                    models.CharField(blank=True, editable=False, max_length=71),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "业务知识",
                "verbose_name_plural": "业务知识库",
                "ordering": ("system_id", "title", "id"),
            },
        ),
        migrations.CreateModel(
            name="TestPlanArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact_id",
                    models.CharField(
                        default=apps.test_platform.models._test_plan_artifact_id,
                        editable=False,
                        max_length=35,
                        unique=True,
                        verbose_name="测试计划编号",
                    ),
                ),
                (
                    "source_kind",
                    models.CharField(
                        choices=[
                            ("generated", "需求生成"),
                            ("imported", "已有产物导入"),
                        ],
                        default="generated",
                        editable=False,
                        max_length=16,
                        verbose_name="产物来源",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="测试计划名称"),
                ),
                (
                    "test_categories",
                    models.JSONField(
                        default=list, editable=False, verbose_name="测试分类"
                    ),
                ),
                (
                    "design_id",
                    models.CharField(
                        db_index=True, max_length=192, verbose_name="设计编号"
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="版本")),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True, max_length=71, verbose_name="内容 Hash"
                    ),
                ),
                (
                    "generation_result",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                (
                    "review_payload",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                (
                    "approved_bundle",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("review", "待审批"),
                            ("blocked", "生成结果已阻塞"),
                            ("changes", "退回修改"),
                            ("approved", "已审批"),
                            ("error", "处理失败"),
                        ],
                        db_index=True,
                        default="review",
                        max_length=16,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "review_comments",
                    models.TextField(blank=True, verbose_name="审批意见"),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, editable=False, verbose_name="最近错误"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "审批测试计划",
                "verbose_name_plural": "审批测试计划",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="TestResourceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_id",
                    models.CharField(
                        default=apps.test_platform.models._resource_profile_id,
                        editable=False,
                        max_length=40,
                        unique=True,
                        verbose_name="配置编号",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="例如：账号系统测试资源。",
                        max_length=200,
                        verbose_name="配置名称",
                    ),
                ),
                (
                    "system_id",
                    models.CharField(
                        blank=True,
                        help_text="稳定的系统编号，例如 account-web；用于关联各层产物。",
                        max_length=128,
                        verbose_name="被测系统标识",
                    ),
                ),
                (
                    "environment",
                    models.CharField(
                        default="test",
                        help_text="例如 local、test 或 staging；不同环境的资源和产物不会混用。",
                        max_length=128,
                        verbose_name="测试环境",
                    ),
                ),
                (
                    "ui_procedure_database",
                    models.FileField(
                        blank=True,
                        help_text="上传一个网站对应的 SQLite UI 函数资产库，例如 127.0.0.1.sqlite。",
                        upload_to="test_platform/resources/ui-procedures/%Y/%m/",
                        verbose_name="沉淀资产库",
                    ),
                ),
                (
                    "api_openapi_file",
                    models.FileField(
                        blank=True,
                        help_text="可上传 OpenAPI，也可上传包含 method、path 和参数说明的常见文档。",
                        upload_to="test_platform/resources/openapi/%Y/%m/",
                        verbose_name="接口资料文件（可选）",
                    ),
                ),
                (
                    "api_asset_text",
                    models.TextField(
                        blank=True,
                        help_text="没有现成文件时，可直接描述可调用接口及参数；模型会整理为内部接口目录。",
                        verbose_name="接口资料说明（可选）",
                    ),
                ),
                (
                    "api_base_url",
                    models.URLField(
                        blank=True,
                        help_text="例如 https://staging.example.test/api。",
                        verbose_name="被测 API 基础地址",
                    ),
                ),
                (
                    "database_query_file",
                    models.FileField(
                        blank=True,
                        help_text="可上传表结构、DDL、数据字典或数据库说明，不要包含密码或连接串。",
                        upload_to="test_platform/resources/database/%Y/%m/",
                        verbose_name="数据库资料文件（可选）",
                    ),
                ),
                (
                    "database_asset_text",
                    models.TextField(
                        blank=True,
                        help_text="可直接描述方言、可测试的表和字段；模型会整理为只读数据库边界。",
                        verbose_name="数据库资料说明（可选）",
                    ),
                ),
                (
                    "database_connection_ref",
                    models.CharField(
                        blank=True,
                        help_text="只填写运行环境中已登记的连接名称，不填写密码或连接串。",
                        max_length=128,
                        verbose_name="数据库连接引用",
                    ),
                ),
                (
                    "performance_profile_file",
                    models.FileField(
                        blank=True,
                        help_text="可上传性能要求、历史方案或现有配置，格式不必固定。",
                        upload_to="test_platform/resources/performance/%Y/%m/",
                        verbose_name="性能资料文件（可选）",
                    ),
                ),
                (
                    "performance_asset_text",
                    models.TextField(
                        blank=True,
                        help_text="可直接描述目标地址、负载上限和指标；模型会整理为内部性能配置。",
                        verbose_name="性能资料说明（可选）",
                    ),
                ),
                (
                    "port_host",
                    models.CharField(
                        blank=True,
                        help_text="填写主机名或 IP，不填写协议和路径。",
                        max_length=253,
                        verbose_name="被测主机",
                    ),
                ),
                (
                    "port_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="被测 TCP 端口"
                    ),
                ),
                (
                    "normalized_resource_data",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                (
                    "normalized_resource_source_hash",
                    models.CharField(blank=True, editable=False, max_length=71),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        db_index=True, default=True, verbose_name="启用"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "测试资源配置",
                "verbose_name_plural": "测试资源配置",
                "ordering": ["system_id", "environment", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExecutionPlanArtifact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "artifact_id",
                    models.CharField(
                        default=apps.test_platform.models._execution_plan_artifact_id,
                        editable=False,
                        max_length=35,
                        unique=True,
                        verbose_name="执行计划编号",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="执行计划名称"),
                ),
                (
                    "test_categories",
                    models.JSONField(
                        default=list, editable=False, verbose_name="测试分类"
                    ),
                ),
                (
                    "plan_id",
                    models.CharField(
                        db_index=True, max_length=192, verbose_name="计划编号"
                    ),
                ),
                ("version", models.PositiveIntegerField(verbose_name="版本")),
                (
                    "content_hash",
                    models.CharField(
                        db_index=True, max_length=71, verbose_name="内容 Hash"
                    ),
                ),
                (
                    "catalog_snapshot",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                (
                    "runtime_config_hash",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=71,
                        verbose_name="运行资源 Hash",
                    ),
                ),
                (
                    "execution_input",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        editable=False,
                        verbose_name="已冻结运行输入",
                    ),
                ),
                (
                    "compilation_result",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                (
                    "review_payload",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                (
                    "approved_bundle",
                    models.JSONField(blank=True, default=dict, editable=False),
                ),
                ("artifact_root_ref", models.CharField(editable=False, max_length=512)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("generating", "生成中"),
                            ("review", "待审批"),
                            ("blocked", "生成结果已阻塞"),
                            ("changes", "退回修改"),
                            ("approved", "已审批"),
                            ("superseded", "已被新版本替代"),
                            ("error", "处理失败"),
                        ],
                        db_index=True,
                        default="review",
                        max_length=16,
                        verbose_name="审批状态",
                    ),
                ),
                (
                    "generation_progress",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        editable=False,
                        verbose_name="生成进度",
                    ),
                ),
                (
                    "review_comments",
                    models.TextField(blank=True, verbose_name="审批意见"),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, editable=False, verbose_name="最近错误"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "source_test_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_plans",
                        to="test_platform.testplanartifact",
                        verbose_name="来源测试计划",
                    ),
                ),
                (
                    "resource_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="execution_plan_artifacts",
                        to="test_platform.testresourceprofile",
                        verbose_name="测试资源",
                    ),
                ),
            ],
            options={
                "verbose_name": "审批执行计划",
                "verbose_name_plural": "审批执行计划",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="testplanartifact",
            name="resource_profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="test_plan_artifacts",
                to="test_platform.testresourceprofile",
                verbose_name="测试资源",
            ),
        ),
        migrations.CreateModel(
            name="TestWorkflow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "workflow_id",
                    models.CharField(
                        default=apps.test_platform.models._workflow_id,
                        editable=False,
                        max_length=35,
                        unique=True,
                        verbose_name="工作单号",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="测试任务名称（可选）"
                    ),
                ),
                (
                    "requirement_text",
                    models.TextField(blank=True, verbose_name="需求原文"),
                ),
                (
                    "requirement_file",
                    models.FileField(
                        blank=True,
                        help_text="可上传 DOCX、PDF、Markdown、Excel、JSON、YAML、ReqIF 等常见需求文件。",
                        upload_to="test_platform/requirements/%Y/%m/",
                        verbose_name="主需求文档",
                    ),
                ),
                (
                    "request_id",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="外部需求号"
                    ),
                ),
                (
                    "system_id",
                    models.CharField(
                        default="unknown", max_length=128, verbose_name="目标系统"
                    ),
                ),
                (
                    "target_environment",
                    models.CharField(
                        default="unknown", max_length=128, verbose_name="目标环境"
                    ),
                ),
                (
                    "coverage_by_category",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="按测试分类保存适用的覆盖方式。",
                        verbose_name="各分类覆盖方式",
                    ),
                ),
                (
                    "allowed_channels",
                    models.JSONField(default=list, verbose_name="测试分类"),
                ),
                (
                    "knowledge_scope_ids",
                    models.JSONField(blank=True, default=list, verbose_name="知识范围"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "待生成测试计划"),
                            ("design_generating", "测试计划生成中"),
                            ("design_review", "测试计划待审核"),
                            ("design_changes", "测试计划待修改"),
                            ("design_approved", "测试计划已审核"),
                            ("error", "处理失败"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                        verbose_name="当前阶段",
                    ),
                ),
                (
                    "generation_progress",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        editable=False,
                        verbose_name="生成进度",
                    ),
                ),
                (
                    "last_error",
                    models.TextField(
                        blank=True, editable=False, verbose_name="最近错误"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "resource_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="workflows",
                        to="test_platform.testresourceprofile",
                        verbose_name="测试资源",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试任务",
                "verbose_name_plural": "测试任务",
                "ordering": ["-updated_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="testplanartifact",
            name="source_intent",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="test_plan_artifacts",
                to="test_platform.testworkflow",
                verbose_name="来源测试意图",
            ),
        ),
        migrations.CreateModel(
            name="TestIntentImport",
            fields=[],
            options={
                "verbose_name": "导入测试意图",
                "verbose_name_plural": "导入测试意图",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("test_platform.testworkflow",),
        ),
        migrations.CreateModel(
            name="TestExecutionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.CharField(
                        max_length=128, unique=True, verbose_name="运行批次号"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "排队中"),
                            ("running", "运行中"),
                            ("passed", "通过"),
                            ("failed", "失败"),
                            ("blocked", "阻断"),
                            ("error", "错误"),
                            ("inconclusive", "未定"),
                            ("dry_run", "预检"),
                        ],
                        db_index=True,
                        default="running",
                        max_length=16,
                        verbose_name="运行状态",
                    ),
                ),
                (
                    "report_status",
                    models.CharField(
                        choices=[
                            ("pending", "待生成"),
                            ("available", "可用"),
                            ("failed", "生成失败"),
                        ],
                        default="pending",
                        max_length=16,
                        verbose_name="报告状态",
                    ),
                ),
                ("design_id", models.CharField(blank=True, max_length=192)),
                ("design_version", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "plan_id",
                    models.CharField(blank=True, db_index=True, max_length=192),
                ),
                ("plan_version", models.PositiveIntegerField(blank=True, null=True)),
                ("plan_content_hash", models.CharField(blank=True, max_length=71)),
                ("artifact_set_hash", models.CharField(blank=True, max_length=71)),
                ("target_system_id", models.CharField(blank=True, max_length=192)),
                ("target_environment", models.CharField(blank=True, max_length=192)),
                (
                    "started_at",
                    models.DateTimeField(db_index=True, verbose_name="开始时间"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="结束时间"
                    ),
                ),
                (
                    "duration_ms",
                    models.FloatField(
                        blank=True, null=True, verbose_name="耗时（毫秒）"
                    ),
                ),
                ("storage_root_ref", models.CharField(max_length=1024)),
                ("manifest_path", models.CharField(blank=True, max_length=1024)),
                ("report_paths", models.JSONField(blank=True, default=dict)),
                ("report_content_hash", models.CharField(blank=True, max_length=71)),
                ("result_summary", models.JSONField(blank=True, default=dict)),
                ("errors", models.JSONField(blank=True, default=list)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "execution_plan",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="test_platform.executionplanartifact",
                        verbose_name="执行计划产物",
                    ),
                ),
                (
                    "resource_profile",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="runs",
                        to="test_platform.testresourceprofile",
                        verbose_name="执行时测试资源配置",
                    ),
                ),
            ],
            options={
                "verbose_name": "执行历史",
                "verbose_name_plural": "执行历史",
                "ordering": ["-started_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["plan_id", "started_at"], name="tp_run_plan_started_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status__in", ("queued", "running"))),
                        fields=("execution_plan",),
                        name="tp_one_active_run_per_plan",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="executionplanartifact",
            constraint=models.UniqueConstraint(
                fields=("plan_id", "version", "content_hash"),
                name="tp_unique_plan_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionplanartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "generating")),
                fields=("source_test_plan",),
                name="tp_one_generating_plan_per_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="executionplanartifact",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "approved")),
                fields=("source_test_plan",),
                name="tp_one_approved_plan_per_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="testplanartifact",
            constraint=models.UniqueConstraint(
                fields=("design_id", "version", "content_hash"),
                name="tp_unique_design_revision",
            ),
        ),
    ]
