# Generated by Django 5.2.16 on 2026-07-28 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_platform", "0002_testresourceprofile_ui_agent_assets"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="executionplanartifact",
            name="tp_one_approved_plan_per_source",
        ),
        migrations.AddField(
            model_name="executionplanartifact",
            name="is_marked",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="已标记"
            ),
        ),
        migrations.AddField(
            model_name="testexecutionrun",
            name="is_marked",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="已标记"
            ),
        ),
        migrations.AddField(
            model_name="testplanartifact",
            name="is_marked",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="已标记"
            ),
        ),
        migrations.AddField(
            model_name="testworkflow",
            name="is_marked",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="已标记"
            ),
        ),
    ]
