# Generated by Django 5.2.16 on 2026-07-28 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "test_platform",
            "0003_remove_executionplanartifact_tp_one_approved_plan_per_source_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="executionplanartifact",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "执行计划",
                "verbose_name_plural": "执行计划",
            },
        ),
        migrations.AlterModelOptions(
            name="testplanartifact",
            options={
                "ordering": ["-created_at", "-id"],
                "verbose_name": "测试计划",
                "verbose_name_plural": "测试计划",
            },
        ),
    ]
