# Generated by Django 5.2.16 on 2026-07-28 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_platform", "0004_alter_executionplanartifact_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testplanartifact",
            name="source_intent",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="test_plan_artifacts",
                to="test_platform.testworkflow",
                verbose_name="来源测试意图",
            ),
        ),
        migrations.AlterField(
            model_name="executionplanartifact",
            name="source_test_plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="execution_plans",
                to="test_platform.testplanartifact",
                verbose_name="来源测试计划",
            ),
        ),
        migrations.AlterField(
            model_name="testexecutionrun",
            name="execution_plan",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="test_platform.executionplanartifact",
                verbose_name="执行计划产物",
            ),
        ),
    ]
