"""第一层：原始需求 + 前端选择 -> 可审核逻辑 TestDesign。"""

from .builder import DefaultDesignBuilder
from .contracts import (
    ApprovedKnowledge,
    ApprovedTestDesignBundle,
    CleanupGoal,
    CleanupGoalCandidate,
    DataRequirement,
    DataRequirementCandidate,
    DesignText,
    DesignSelections,
    ExpectedResult,
    ExpectedResultCandidate,
    LogicalScenario,
    LogicalScenarioCandidate,
    Operation,
    OperationCandidate,
    RequiredState,
    RequiredStateCandidate,
    RequirementInput,
    RequirementSnapshot,
    ReviewDecision,
    TargetSelection,
    TestChannel,
    TestDesign,
    TestDesignCandidate,
    TestDesignInputSnapshot,
    TestDesignRequest,
    TestDesignReview,
    TestDesignValidationReport,
    TestTechnique,
)
from .knowledge import (
    ApprovedKnowledgeSourceStore,
    InMemoryApprovedKnowledgeResolver,
    MilvusApprovedKnowledgeResolver,
)
from .prompt_builder import DefaultDesignPromptBuilder
from .service import TestDesignGenerationResult, TestDesignPipeline, build_default_pipeline

__all__ = [
    "ApprovedKnowledge",
    "ApprovedTestDesignBundle",
    "CleanupGoal",
    "CleanupGoalCandidate",
    "DataRequirement",
    "DataRequirementCandidate",
    "DefaultDesignBuilder",
    "DefaultDesignPromptBuilder",
    "DesignText",
    "DesignSelections",
    "ExpectedResult",
    "ExpectedResultCandidate",
    "InMemoryApprovedKnowledgeResolver",
    "ApprovedKnowledgeSourceStore",
    "MilvusApprovedKnowledgeResolver",
    "LogicalScenario",
    "LogicalScenarioCandidate",
    "Operation",
    "OperationCandidate",
    "RequiredState",
    "RequiredStateCandidate",
    "RequirementInput",
    "RequirementSnapshot",
    "ReviewDecision",
    "TargetSelection",
    "TestChannel",
    "TestDesign",
    "TestDesignCandidate",
    "TestDesignGenerationResult",
    "TestDesignInputSnapshot",
    "TestDesignPipeline",
    "TestDesignRequest",
    "TestDesignReview",
    "TestDesignValidationReport",
    "TestTechnique",
    "build_default_pipeline",
]
